"""Inspect tab for viewing embedded command metadata in generated videos."""

from __future__ import annotations

from pathlib import Path

from textual import on
from textual.app import ComposeResult
from textual.containers import Horizontal, VerticalScroll
from textual.widgets import Button, Label, Static

from ltx_tui_wrapper.options import GenerateOptions
from ltx_tui_wrapper.output_paths import latest_output_path
from ltx_tui_wrapper.tui.tabs.shared import TabMixinBase
from ltx_tui_wrapper.tui.widgets import CopyInput
from ltx_tui_wrapper.video_metadata import (
    METADATA_KEY,
    format_stored_commands,
    read_metadata,
)


class InspectTabMixin(TabMixinBase):
    """Compose, events, and display logic for the Inspect tab."""

    def _compose_inspect_tab(self) -> ComposeResult:
        with VerticalScroll():
            yield Static(
                "Pick a video generated by ltx-tui to view the command stored in its metadata.",
                classes="field-hint",
            )
            yield Label("Input video", classes="field-label")
            with Horizontal(classes="field-row"):
                yield CopyInput(
                    placeholder="path/to/video.mp4",
                    id="inspect-input",
                )
                yield Button("Browse…", id="browse-inspect-input")
            with Horizontal(classes="field-row"):
                yield Label("Saved command", classes="field-label")
                yield Button("Copy", id="copy-inspect-metadata", disabled=True)
            yield Static(
                "Select a video to view its embedded command metadata.",
                id="inspect-command-preview",
                classes="command-preview",
            )

    def _mount_inspect_tab(self) -> None:
        if self._inspect_input is not None:
            self.query_one("#inspect-input", CopyInput).value = self._inspect_input
        self._refresh_inspect_preview()

    def apply_last_inspect(self, last_run: GenerateOptions) -> None:
        input_path = latest_output_path(last_run.output)
        self.query_one("#inspect-input", CopyInput).value = input_path
        self._refresh_inspect_preview()
        self._set_status("Applied last run output for inspection.")

    @on(Button.Pressed, "#browse-inspect-input")
    def browse_inspect_input(self) -> None:
        from ltx_tui_wrapper.file_dialog import VIDEO_EXTENSIONS

        self._browse_into_input(
            "#inspect-input",
            self._browse_start_dir("#inspect-input"),
            extensions=VIDEO_EXTENSIONS,
        )

    @on(CopyInput.Changed, "#inspect-input")
    def inspect_input_changed(self) -> None:
        self._refresh_inspect_preview()

    @on(Button.Pressed, "#copy-inspect-metadata")
    def copy_inspect_metadata_pressed(self) -> None:
        self._copy_inspect_metadata()

    def action_copy_inspect_metadata(self) -> None:
        if self._active_tab() != "inspect":
            return
        self._copy_inspect_metadata()

    def _inspect_metadata_text(self) -> str | None:
        input_text = self.query_one("#inspect-input", CopyInput).value.strip()
        if not input_text:
            return None
        path = Path(input_text).expanduser()
        if not path.is_file():
            return None
        if not read_metadata(path).get(METADATA_KEY):
            return None
        return format_stored_commands(path)

    def _copy_inspect_metadata(self) -> None:
        text = self._inspect_metadata_text()
        if not text:
            self._set_status("No metadata to copy.")
            return
        self.copy_to_clipboard(text)
        self._set_status("Copied metadata to clipboard.")

    def _refresh_inspect_preview(self) -> None:
        preview = self.query_one("#inspect-command-preview", Static)
        copy_button = self.query_one("#copy-inspect-metadata", Button)
        input_text = self.query_one("#inspect-input", CopyInput).value.strip()
        if not input_text:
            preview.update(
                "Select a video to view its embedded command metadata."
            )
            copy_button.disabled = True
            return
        preview.update(format_stored_commands(Path(input_text).expanduser()))
        copy_button.disabled = self._inspect_metadata_text() is None

    def _start_inspect_run(self) -> None:
        self._refresh_inspect_preview()
