"""Extend from an existing generated video by reusing embedded generate args."""

from __future__ import annotations

import shlex
import shutil
import sys
import tempfile
import time
from dataclasses import replace
from pathlib import Path

from ltx_tui_wrapper.batch_cli import format_elapsed
from ltx_tui_wrapper.extend import (
    _require_tool,
    concat_videos,
    extract_last_frame,
    parse_target_duration,
    probe_video_duration,
)
from ltx_tui_wrapper.options import GenerateOptions
from ltx_tui_wrapper.output_paths import (
    archive_extend_from_original,
    discover_extend_from_inputs,
    extended_output_exists,
    resolve_extend_from_output_path,
)
from ltx_tui_wrapper.parsing import (
    GenerateParseError,
    build_command_argv,
    format_command,
    parse_generate_argv,
)
from ltx_tui_wrapper.progress import print_failure, print_status_band
from ltx_tui_wrapper.retries import run_with_retries
from ltx_tui_wrapper.runner import prevent_sleep
from ltx_tui_wrapper.upscale import upscale_image
from ltx_tui_wrapper.video_metadata import (
    GENERATE_COMMANDS_METADATA_KEY,
    METADATA_KEY,
    current_invocation,
    format_generate_commands,
    invocation_with_output,
    read_command_metadata,
    write_metadata,
)

EXTEND_FROM_OK = 0
EXTEND_FROM_SKIP_LONG = 2


def load_generate_options_from_video(video_path: str | Path) -> GenerateOptions:
    """Load generate options from a video's embedded metadata command."""
    path = Path(video_path).expanduser()
    if not path.is_file():
        raise ValueError(f"Input video not found: {path}")
    metadata_command = read_command_metadata(path)
    if metadata_command is None:
        raise ValueError(
            "No embedded generate command found in input video metadata. "
            "Only videos generated by ltx-tui can be extended from."
        )
    try:
        argv = shlex.split(metadata_command)
    except ValueError as exc:
        raise ValueError("Invalid embedded command metadata.") from exc
    try:
        return parse_generate_argv(argv)
    except GenerateParseError as exc:
        raise ValueError(
            "Could not parse embedded generate command from input metadata."
        ) from exc


def extend_video_from(
    *,
    input_video: Path,
    target_duration: float,
    max_retries: int,
    final_output: str | None = None,
    keep_segments: bool = False,
    upscale: bool = False,
    upscale_model: str = "realesrgan-x4plus",
    upscale_scale: int | None = None,
    realesrgan_bin: str | None = None,
    models_dir: str | None = None,
) -> int:
    """Continue *input_video* by chaining I2V segments from its last frame."""
    input_video = input_video.expanduser().resolve()
    if not input_video.is_file():
        raise SystemExit(f"Input video not found: {input_video}")

    base_options = load_generate_options_from_video(input_video)

    _require_tool("ffmpeg")
    _require_tool("ffprobe")

    segments: list[Path] = [input_video]
    generated_segments: list[Path] = []
    segment_commands: list[list[str]] = []
    total_duration = probe_video_duration(input_video)
    segment_index = 0
    work_dir = Path(tempfile.mkdtemp(prefix="ltx-tui-extend-from-"))
    extend_started = time.perf_counter()

    print(
        f"Extending {input_video.name} to > {target_duration:.1f}s "
        f"(retry up to {max_retries} time(s) per segment, seed {base_options.seed}).",
        flush=True,
    )
    print(
        f"Input duration: {total_duration:.2f}s. Working directory: {work_dir}",
        flush=True,
    )

    if total_duration >= target_duration:
        print(
            f"Skipping {input_video.name}: already {total_duration:.2f}s "
            f"(target {target_duration:.1f}s).",
            flush=True,
        )
        shutil.rmtree(work_dir, ignore_errors=True)
        return EXTEND_FROM_SKIP_LONG

    try:
        frame_path = work_dir / "input_last.png"
        extract_last_frame(input_video, frame_path)
        if upscale:
            upscaled_frame_path = work_dir / "input_last_upscaled.png"
            try:
                upscale_image(
                    frame_path,
                    upscaled_frame_path,
                    model=upscale_model,
                    scale=upscale_scale,
                    realesrgan_bin=realesrgan_bin,
                    models_dir=models_dir,
                )
            except (RuntimeError, ValueError) as exc:
                print_failure(
                    f"Failed to upscale last frame from {input_video.name}",
                    details=str(exc),
                )
                return 1
            frame_path = upscaled_frame_path

        current_options = base_options

        with prevent_sleep():
            while total_duration < target_duration:
                segment_index += 1
                segment_output = work_dir / f"segment_{segment_index:03d}.mp4"
                run_options = replace(
                    current_options,
                    output=str(segment_output),
                    image_specs=(str(frame_path),),
                )

                argv = build_command_argv(run_options)
                segment_commands.append(argv)
                label = f"Segment {segment_index}"
                print(f"[{label}] {format_command(run_options)}", flush=True)
                exit_code, elapsed = run_with_retries(
                    argv,
                    max_retries=max_retries,
                    label=label,
                )
                if exit_code != 0:
                    attempts = max(1, max_retries)
                    print_status_band(
                        f"{label} failed with exit code {exit_code} "
                        f"after {format_elapsed(elapsed)} ({attempts} attempt(s)).",
                        success=False,
                    )
                    return exit_code

                segment_path = Path(run_options.output)
                if not segment_path.is_file():
                    print_status_band(
                        f"{label} failed: expected output file missing ({segment_path}).",
                        success=False,
                    )
                    return 1

                segment_duration = probe_video_duration(segment_path)
                segments.append(segment_path)
                generated_segments.append(segment_path)
                total_duration += segment_duration
                print_status_band(
                    f"Segment {segment_index}: {segment_duration:.2f}s "
                    f"(total {total_duration:.2f}s / {target_duration:.1f}s) "
                    f"in {format_elapsed(elapsed)}.",
                    success=True,
                )

                if total_duration >= target_duration:
                    break

                frame_path = work_dir / f"segment_{segment_index:03d}_last.png"
                extract_last_frame(segment_path, frame_path)
                if upscale:
                    upscaled_frame_path = (
                        work_dir / f"segment_{segment_index:03d}_last_upscaled.png"
                    )
                    try:
                        upscale_image(
                            frame_path,
                            upscaled_frame_path,
                            model=upscale_model,
                            scale=upscale_scale,
                            realesrgan_bin=realesrgan_bin,
                            models_dir=models_dir,
                        )
                    except (RuntimeError, ValueError) as exc:
                        print_failure(
                            f"Failed to upscale last frame for segment {segment_index}",
                            details=str(exc),
                        )
                        return 1
                    frame_path = upscaled_frame_path
                current_options = run_options

        out_path = Path(
            resolve_extend_from_output_path(str(input_video), final_output)
        )
        out_path.parent.mkdir(parents=True, exist_ok=True)
        print(
            f"Concatenating {len(segments)} segment(s) -> {out_path}",
            flush=True,
        )
        concat_videos(segments, out_path)
        write_metadata(
            out_path,
            {
                METADATA_KEY: shlex.join(
                    invocation_with_output(current_invocation(), out_path)
                ),
                GENERATE_COMMANDS_METADATA_KEY: format_generate_commands(segment_commands),
            },
        )
        archived = archive_extend_from_original(input_video)
        final_duration = probe_video_duration(out_path)
        total_elapsed = time.perf_counter() - extend_started
        print(
            f"Extended video ready: {out_path} ({final_duration:.2f}s) "
            f"in {format_elapsed(total_elapsed)}.",
            flush=True,
        )
        print(f"Archived original video: {archived}", flush=True)
        return EXTEND_FROM_OK
    finally:
        if not keep_segments:
            for segment in generated_segments:
                segment.unlink(missing_ok=True)
            shutil.rmtree(work_dir, ignore_errors=True)


def run_extend_from_inputs(
    *,
    input_path: Path,
    target_duration: float,
    max_retries: int,
    final_output: str | None = None,
    keep_segments: bool = False,
    continue_on_error: bool = False,
    upscale: bool = False,
    upscale_model: str = "realesrgan-x4plus",
    upscale_scale: int | None = None,
    realesrgan_bin: str | None = None,
    models_dir: str | None = None,
) -> int:
    """Extend every candidate video under *input_path* (file or directory).

    Re-running the same folder skips videos that already have an extended output
    under ``extended/`` (``<stem>_extended.mp4`` or ``<stem>_extended_<timestamp>.mp4``),
    so interrupted runs are resumable. After each successful extend, the original
    video is moved into ``original/``.
    """
    videos = discover_extend_from_inputs(input_path)
    extended = 0
    skipped_done = 0
    skipped_long = 0
    failures = 0
    batch_started = time.perf_counter()

    with prevent_sleep():
        for index, video in enumerate(videos, start=1):
            existing = extended_output_exists(video)
            if existing is not None:
                skipped_done += 1
                print(
                    f"[{index}/{len(videos)}] Skipping {video.name} "
                    f"(already extended -> {existing.name})",
                    flush=True,
                )
                continue

            print(
                f"[{index}/{len(videos)}] Extending {video.name} "
                f"to > {target_duration:.1f}s",
                flush=True,
            )
            per_video_output = final_output if len(videos) == 1 else None
            exit_code = extend_video_from(
                input_video=video,
                target_duration=target_duration,
                max_retries=max_retries,
                final_output=per_video_output,
                keep_segments=keep_segments,
                upscale=upscale,
                upscale_model=upscale_model,
                upscale_scale=upscale_scale,
                realesrgan_bin=realesrgan_bin,
                models_dir=models_dir,
            )
            if exit_code == EXTEND_FROM_OK:
                extended += 1
            elif exit_code == EXTEND_FROM_SKIP_LONG:
                skipped_long += 1
            else:
                failures += 1
                print(
                    f"Extend-from failed for {video.name} with exit code {exit_code}.",
                    file=sys.stderr,
                )
                if not continue_on_error:
                    return exit_code

    total_elapsed = time.perf_counter() - batch_started
    print(
        f"Extend-from complete: {extended} extended, "
        f"{skipped_done} skipped (already done), "
        f"{skipped_long} skipped (already long enough), "
        f"{failures} failed in {format_elapsed(total_elapsed)}.",
        flush=True,
    )
    if failures:
        return 1
    return 0


__all__ = [
    "EXTEND_FROM_OK",
    "EXTEND_FROM_SKIP_LONG",
    "extend_video_from",
    "load_generate_options_from_video",
    "parse_target_duration",
    "run_extend_from_inputs",
]
