"""Extend from an existing generated video by reusing embedded generate args."""

from __future__ import annotations

import json
import re
import shlex
import shutil
import sys
import time
from dataclasses import replace
from pathlib import Path

from ltx_tui_wrapper.batch_cli import format_elapsed
from ltx_tui_wrapper.extend import (
    _require_tool,
    concat_videos,
    extract_last_frame,
    parse_target_duration,
    probe_video_duration,
)
from ltx_tui_wrapper.options import GenerateOptions
from ltx_tui_wrapper.output_paths import (
    archive_extend_from_original,
    discover_extend_from_inputs,
    extend_from_segments_dir,
    extended_output_exists,
    resolve_extend_from_output_path,
)
from ltx_tui_wrapper.parsing import (
    GenerateParseError,
    build_command_argv,
    format_command,
    parse_generate_argv,
)
from ltx_tui_wrapper.progress import print_failure, print_status_band
from ltx_tui_wrapper.retries import run_with_retries
from ltx_tui_wrapper.runner import prevent_sleep
from ltx_tui_wrapper.upscale import upscale_image
from ltx_tui_wrapper.video_metadata import (
    GENERATE_COMMANDS_METADATA_KEY,
    METADATA_KEY,
    current_invocation,
    format_generate_commands,
    invocation_with_output,
    read_command_metadata,
    write_metadata,
)

EXTEND_FROM_OK = 0
EXTEND_FROM_SKIP_LONG = 2
_SEGMENT_FILE = re.compile(r"^segment_(\d{3})\.mp4$")
_PROGRESS_FILE = "progress.json"


def load_generate_options_from_video(video_path: str | Path) -> GenerateOptions:
    """Load generate options from a video's embedded metadata command."""
    path = Path(video_path).expanduser()
    if not path.is_file():
        raise ValueError(f"Input video not found: {path}")
    metadata_command = read_command_metadata(path)
    if metadata_command is None:
        raise ValueError(
            "No embedded generate command found in input video metadata. "
            "Only videos generated by ltx-tui can be extended from."
        )
    try:
        argv = shlex.split(metadata_command)
    except ValueError as exc:
        raise ValueError("Invalid embedded command metadata.") from exc
    try:
        return parse_generate_argv(argv)
    except GenerateParseError as exc:
        raise ValueError(
            "Could not parse embedded generate command from input metadata."
        ) from exc


def _write_extend_progress(
    work_dir: Path,
    *,
    input_video: Path,
    segment_commands: list[list[str]],
) -> None:
    work_dir.mkdir(parents=True, exist_ok=True)
    payload = {
        "input_video": str(input_video.resolve()),
        "segment_commands": [shlex.join(command) for command in segment_commands],
    }
    (work_dir / _PROGRESS_FILE).write_text(json.dumps(payload, indent=2) + "\n")


def _read_extend_progress(
    work_dir: Path,
) -> tuple[Path | None, list[list[str]]]:
    progress_path = work_dir / _PROGRESS_FILE
    if not progress_path.is_file():
        return None, []

    try:
        payload = json.loads(progress_path.read_text())
    except (OSError, json.JSONDecodeError):
        return None, []

    input_video: Path | None = None
    raw_input = payload.get("input_video")
    if isinstance(raw_input, str) and raw_input:
        input_video = Path(raw_input)

    segment_commands: list[list[str]] = []
    raw_commands = payload.get("segment_commands")
    if isinstance(raw_commands, list):
        for item in raw_commands:
            if not isinstance(item, str) or not item:
                continue
            try:
                segment_commands.append(shlex.split(item))
            except ValueError:
                continue

    return input_video, segment_commands


def scan_extend_from_segments(work_dir: Path) -> list[Path]:
    """Return completed segment paths ``segment_001`` through ``segment_NNN``."""
    if not work_dir.is_dir():
        return []

    indexed: dict[int, Path] = {}
    for path in work_dir.iterdir():
        if not path.is_file():
            continue
        match = _SEGMENT_FILE.match(path.name)
        if match:
            indexed[int(match.group(1))] = path

    completed: list[Path] = []
    index = 1
    while index in indexed:
        path = indexed[index]
        try:
            probe_video_duration(path)
        except RuntimeError:
            path.unlink(missing_ok=True)
            break
        completed.append(path)
        index += 1

    for orphan_index, orphan_path in indexed.items():
        if orphan_index > len(completed):
            orphan_path.unlink(missing_ok=True)

    return completed


def _segment_commands_from_paths(segments: list[Path]) -> list[list[str]]:
    commands: list[list[str]] = []
    for segment in segments:
        metadata = read_command_metadata(segment)
        if metadata is None:
            continue
        try:
            commands.append(shlex.split(metadata))
        except ValueError:
            continue
    return commands


def _prepare_segment_frame(
    *,
    source_video: Path,
    work_dir: Path,
    frame_basename: str,
    upscale: bool,
    upscale_model: str,
    upscale_scale: int | None,
    realesrgan_bin: str | None,
    models_dir: str | None,
    failure_label: str,
) -> Path | None:
    if upscale:
        upscaled_frame_path = work_dir / f"{frame_basename}_upscaled.png"
        if upscaled_frame_path.is_file():
            return upscaled_frame_path
    else:
        frame_path = work_dir / f"{frame_basename}.png"
        if frame_path.is_file():
            return frame_path

    frame_path = work_dir / f"{frame_basename}.png"
    extract_last_frame(source_video, frame_path)
    if not upscale:
        return frame_path

    upscaled_frame_path = work_dir / f"{frame_basename}_upscaled.png"
    try:
        upscale_image(
            frame_path,
            upscaled_frame_path,
            model=upscale_model,
            scale=upscale_scale,
            realesrgan_bin=realesrgan_bin,
            models_dir=models_dir,
        )
    except (RuntimeError, ValueError) as exc:
        print_failure(failure_label, details=str(exc))
        return None
    return upscaled_frame_path


def extend_video_from(
    *,
    input_video: Path,
    target_duration: float,
    max_retries: int,
    final_output: str | None = None,
    keep_segments: bool = False,
    upscale: bool = False,
    upscale_model: str = "realesrgan-x4plus",
    upscale_scale: int | None = None,
    realesrgan_bin: str | None = None,
    models_dir: str | None = None,
) -> int:
    """Continue *input_video* by chaining I2V segments from its last frame."""
    input_video = input_video.expanduser().resolve()
    if not input_video.is_file():
        raise SystemExit(f"Input video not found: {input_video}")

    base_options = load_generate_options_from_video(input_video)

    _require_tool("ffmpeg")
    _require_tool("ffprobe")

    work_dir = extend_from_segments_dir(input_video)
    work_dir.mkdir(parents=True, exist_ok=True)
    extend_started = time.perf_counter()
    exit_code = 1

    print(
        f"Extending {input_video.name} to > {target_duration:.1f}s "
        f"(retry up to {max_retries} time(s) per segment, seed {base_options.seed}).",
        flush=True,
    )
    print(f"Working directory: {work_dir}", flush=True)

    progress_input, segment_commands = _read_extend_progress(work_dir)
    if progress_input is not None and progress_input.resolve() != input_video:
        print(
            f"Warning: progress file references {progress_input.name}, "
            f"but continuing with {input_video.name}.",
            flush=True,
        )

    completed_segments = scan_extend_from_segments(work_dir)
    segment_index = len(completed_segments)
    segments: list[Path] = [input_video, *completed_segments]
    input_duration = probe_video_duration(input_video)
    total_duration = input_duration + sum(
        probe_video_duration(segment) for segment in completed_segments
    )
    if len(segment_commands) < len(completed_segments):
        segment_commands = _segment_commands_from_paths(completed_segments)

    if segment_index > 0:
        print(
            f"Resuming: {segment_index} segment(s) already complete "
            f"({total_duration:.2f}s / {target_duration:.1f}s).",
            flush=True,
        )
    else:
        print(f"Input duration: {input_duration:.2f}s.", flush=True)

    if total_duration >= target_duration:
        if segment_index == 0:
            print(
                f"Skipping {input_video.name}: already {total_duration:.2f}s "
                f"(target {target_duration:.1f}s).",
                flush=True,
            )
            return EXTEND_FROM_SKIP_LONG
        print(
            f"Target duration already reached ({total_duration:.2f}s); "
            "concatenating existing segments.",
            flush=True,
        )

    try:
        _write_extend_progress(
            work_dir,
            input_video=input_video,
            segment_commands=segment_commands,
        )

        if total_duration < target_duration:
            current_options = base_options
            if segment_index == 0:
                frame_source = input_video
                frame_basename = "input_last"
                frame_failure = f"Failed to upscale last frame from {input_video.name}"
            else:
                frame_source = completed_segments[-1]
                frame_basename = f"segment_{segment_index:03d}_last"
                frame_failure = (
                    f"Failed to upscale last frame for segment {segment_index}"
                )

            frame_path = _prepare_segment_frame(
                source_video=frame_source,
                work_dir=work_dir,
                frame_basename=frame_basename,
                upscale=upscale,
                upscale_model=upscale_model,
                upscale_scale=upscale_scale,
                realesrgan_bin=realesrgan_bin,
                models_dir=models_dir,
                failure_label=frame_failure,
            )
            if frame_path is None:
                return 1

            with prevent_sleep():
                while total_duration < target_duration:
                    segment_index += 1
                    segment_output = work_dir / f"segment_{segment_index:03d}.mp4"
                    run_options = replace(
                        current_options,
                        output=str(segment_output),
                        image_specs=(str(frame_path),),
                    )

                    argv = build_command_argv(run_options)
                    segment_commands.append(argv)
                    label = f"Segment {segment_index}"
                    print(f"[{label}] {format_command(run_options)}", flush=True)
                    segment_exit_code, elapsed = run_with_retries(
                        argv,
                        max_retries=max_retries,
                        label=label,
                    )
                    if segment_exit_code != 0:
                        attempts = max(1, max_retries)
                        print_status_band(
                            f"{label} failed with exit code {segment_exit_code} "
                            f"after {format_elapsed(elapsed)} ({attempts} attempt(s)). "
                            f"Re-run to resume from segment {segment_index}.",
                            success=False,
                        )
                        return segment_exit_code

                    segment_path = Path(run_options.output)
                    if not segment_path.is_file():
                        print_status_band(
                            f"{label} failed: expected output file missing ({segment_path}). "
                            f"Re-run to resume from segment {segment_index}.",
                            success=False,
                        )
                        return 1

                    segment_duration = probe_video_duration(segment_path)
                    segments.append(segment_path)
                    total_duration += segment_duration
                    _write_extend_progress(
                        work_dir,
                        input_video=input_video,
                        segment_commands=segment_commands,
                    )
                    print_status_band(
                        f"Segment {segment_index}: {segment_duration:.2f}s "
                        f"(total {total_duration:.2f}s / {target_duration:.1f}s) "
                        f"in {format_elapsed(elapsed)}.",
                        success=True,
                    )

                    if total_duration >= target_duration:
                        break

                    frame_basename = f"segment_{segment_index:03d}_last"
                    frame_path = _prepare_segment_frame(
                        source_video=segment_path,
                        work_dir=work_dir,
                        frame_basename=frame_basename,
                        upscale=upscale,
                        upscale_model=upscale_model,
                        upscale_scale=upscale_scale,
                        realesrgan_bin=realesrgan_bin,
                        models_dir=models_dir,
                        failure_label=(
                            f"Failed to upscale last frame for segment {segment_index}"
                        ),
                    )
                    if frame_path is None:
                        return 1
                    current_options = run_options

        out_path = Path(
            resolve_extend_from_output_path(str(input_video), final_output)
        )
        out_path.parent.mkdir(parents=True, exist_ok=True)
        print(
            f"Concatenating {len(segments)} segment(s) -> {out_path}",
            flush=True,
        )
        concat_videos(segments, out_path)
        write_metadata(
            out_path,
            {
                METADATA_KEY: shlex.join(
                    invocation_with_output(current_invocation(), out_path)
                ),
                GENERATE_COMMANDS_METADATA_KEY: format_generate_commands(segment_commands),
            },
        )
        archived = archive_extend_from_original(input_video)
        final_duration = probe_video_duration(out_path)
        total_elapsed = time.perf_counter() - extend_started
        print(
            f"Extended video ready: {out_path} ({final_duration:.2f}s) "
            f"in {format_elapsed(total_elapsed)}.",
            flush=True,
        )
        print(f"Archived original video: {archived}", flush=True)
        exit_code = EXTEND_FROM_OK
        return exit_code
    finally:
        if exit_code == EXTEND_FROM_OK and not keep_segments:
            shutil.rmtree(work_dir, ignore_errors=True)


def run_extend_from_inputs(
    *,
    input_path: Path,
    target_duration: float,
    max_retries: int,
    final_output: str | None = None,
    keep_segments: bool = False,
    continue_on_error: bool = False,
    upscale: bool = False,
    upscale_model: str = "realesrgan-x4plus",
    upscale_scale: int | None = None,
    realesrgan_bin: str | None = None,
    models_dir: str | None = None,
) -> int:
    """Extend every candidate video under *input_path* (file or directory).

    Re-running the same folder skips videos that already have an extended output
    under ``extended/`` (``<stem>_extended.mp4`` or ``<stem>_extended_<timestamp>.mp4``),
    so interrupted batch runs are resumable. Interrupted segment generation for a
    single video resumes from the last completed segment in ``segments/<stem>/``.
    After each successful extend, the original video is moved into ``original/``.
    """
    videos = discover_extend_from_inputs(input_path)
    extended = 0
    skipped_done = 0
    skipped_long = 0
    failures = 0
    batch_started = time.perf_counter()

    with prevent_sleep():
        for index, video in enumerate(videos, start=1):
            existing = extended_output_exists(video)
            if existing is not None:
                skipped_done += 1
                print(
                    f"[{index}/{len(videos)}] Skipping {video.name} "
                    f"(already extended -> {existing.name})",
                    flush=True,
                )
                continue

            print(
                f"[{index}/{len(videos)}] Extending {video.name} "
                f"to > {target_duration:.1f}s",
                flush=True,
            )
            per_video_output = final_output if len(videos) == 1 else None
            exit_code = extend_video_from(
                input_video=video,
                target_duration=target_duration,
                max_retries=max_retries,
                final_output=per_video_output,
                keep_segments=keep_segments,
                upscale=upscale,
                upscale_model=upscale_model,
                upscale_scale=upscale_scale,
                realesrgan_bin=realesrgan_bin,
                models_dir=models_dir,
            )
            if exit_code == EXTEND_FROM_OK:
                extended += 1
            elif exit_code == EXTEND_FROM_SKIP_LONG:
                skipped_long += 1
            else:
                failures += 1
                print(
                    f"Extend-from failed for {video.name} with exit code {exit_code}.",
                    file=sys.stderr,
                )
                if not continue_on_error:
                    return exit_code

    total_elapsed = time.perf_counter() - batch_started
    print(
        f"Extend-from complete: {extended} extended, "
        f"{skipped_done} skipped (already done), "
        f"{skipped_long} skipped (already long enough), "
        f"{failures} failed in {format_elapsed(total_elapsed)}.",
        flush=True,
    )
    if failures:
        return 1
    return 0


__all__ = [
    "EXTEND_FROM_OK",
    "EXTEND_FROM_SKIP_LONG",
    "extend_video_from",
    "load_generate_options_from_video",
    "parse_target_duration",
    "run_extend_from_inputs",
    "scan_extend_from_segments",
]
